/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 3336edc9d25a1f151f6d4cc89b184a31)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	CLOUDFLARE_WORKER_API_URL: "https://score-splitter-api.yosket87.workers.dev";
	WEBAUTHN_RP_ID: "score-splitter-web.yosket87.workers.dev";
	WEBAUTHN_RP_ORIGIN: "https://score-splitter-web.yosket87.workers.dev";
	WEBAUTHN_RP_NAME: "Score Splitter";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_WORKER_API_URL" | "WEBAUTHN_RP_ID" | "WEBAUTHN_RP_ORIGIN" | "WEBAUTHN_RP_NAME">> {}
}
