/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: da17196e95e25514562c39865f4ebe73)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	CLOUDFLARE_WORKER_API_URL: "https://api.yamawake.app";
	WEBAUTHN_RP_ID: "yamawake.app";
	WEBAUTHN_RP_ORIGIN: "https://app.yamawake.app";
	WEBAUTHN_RP_NAME: "ヤマワケ";
	NEXT_PUBLIC_SITE_URL: "https://yamawake.app";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_WORKER_API_URL" | "WEBAUTHN_RP_ID" | "WEBAUTHN_RP_ORIGIN" | "WEBAUTHN_RP_NAME" | "NEXT_PUBLIC_SITE_URL">> {}
}
