/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 420b68c64eefa8d615e6646e9c2a51be)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	GOOGLE_OAUTH_CLIENT_ID: "";
	GOOGLE_OAUTH_ORIGIN: "https://score-splitter-dev.bluespec.workers.dev" | "https://app.yamawake.app";
	FIREBASE_PROJECT_ID: "yamawake-dev-7e298" | "yamawake-prod";
	FIREBASE_API_KEY: "AIzaSyBJ288f9b-M9BDpdZk4roXRLhYQv69-Qi0" | "AIzaSyD8fbQG7-SVZaZzjkwSkYyqIdb-PXgM6jA";
	FIREBASE_AUTH_DOMAIN: "yamawake-dev-7e298.firebaseapp.com" | "yamawake-prod.firebaseapp.com";
	FIREBASE_AUTH_ORIGIN: "https://score-splitter-dev.bluespec.workers.dev" | "https://app.yamawake.app";
	FIREBASE_GOOGLE_ENABLED: "true";
	FIREBASE_APPLE_ENABLED: "false";
	AI_PROVIDER: "openai";
	OPENAI_CLASSIFICATION_MODEL: "gpt-5-mini";
	OPENAI_DIAGNOSIS_MODEL: "gpt-5-mini";
	WEBAUTHN_RP_ID: "yamawake.app";
	WEBAUTHN_RP_ORIGIN: "https://app.yamawake.app";
	WEBAUTHN_RP_NAME: "ヤマワケ";
	NEXT_PUBLIC_SITE_URL: "https://yamawake.app";
	CLOUDFLARE_WORKER_API_URL?: "https://api.yamawake.app";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface DevEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		GOOGLE_OAUTH_CLIENT_ID: "";
		GOOGLE_OAUTH_ORIGIN: "https://score-splitter-dev.bluespec.workers.dev";
		FIREBASE_PROJECT_ID: "yamawake-dev-7e298";
		FIREBASE_API_KEY: "AIzaSyBJ288f9b-M9BDpdZk4roXRLhYQv69-Qi0";
		FIREBASE_AUTH_DOMAIN: "yamawake-dev-7e298.firebaseapp.com";
		FIREBASE_AUTH_ORIGIN: "https://score-splitter-dev.bluespec.workers.dev";
		FIREBASE_GOOGLE_ENABLED: "true";
		FIREBASE_APPLE_ENABLED: "false";
		AI_PROVIDER: "openai";
		OPENAI_CLASSIFICATION_MODEL: "gpt-5-mini";
		OPENAI_DIAGNOSIS_MODEL: "gpt-5-mini";
		WEBAUTHN_RP_ID: "yamawake.app";
		WEBAUTHN_RP_ORIGIN: "https://app.yamawake.app";
		WEBAUTHN_RP_NAME: "ヤマワケ";
		NEXT_PUBLIC_SITE_URL: "https://yamawake.app";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_OAUTH_CLIENT_ID" | "GOOGLE_OAUTH_ORIGIN" | "FIREBASE_PROJECT_ID" | "FIREBASE_API_KEY" | "FIREBASE_AUTH_DOMAIN" | "FIREBASE_AUTH_ORIGIN" | "FIREBASE_GOOGLE_ENABLED" | "FIREBASE_APPLE_ENABLED" | "AI_PROVIDER" | "OPENAI_CLASSIFICATION_MODEL" | "OPENAI_DIAGNOSIS_MODEL" | "WEBAUTHN_RP_ID" | "WEBAUTHN_RP_ORIGIN" | "WEBAUTHN_RP_NAME" | "NEXT_PUBLIC_SITE_URL" | "CLOUDFLARE_WORKER_API_URL">> {}
}
