import { test, expect } from '@playwright/test'
import { resetMockData, prepareGoogleMock, googleLogin, login } from './helpers'
test.beforeEach(async ({ request }) => resetMockData(request))
test('停止で旧sessionと導線が終了しGoogle設定と復旧案内は継続する', async ({ page }) => {
  await login(page)
  await prepareGoogleMock(page, 'legacy-disabled')
  await page.goto('/2026/02')
  await expect(page).toHaveURL(/\/login/)
  await expect(page.getByPlaceholder('パスワード')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'パスキーでログイン' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: /Google.*復旧/ })).toBeVisible()
  await googleLogin(page)
  await expect(page).toHaveURL(/\/\d{4}\/\d{2}/)
  await page.goto('/settings')
  await expect(page.getByText('a.very-long-account-name-for-layout@example.com', { exact: true })).toBeVisible()
  await expect(page.getByText('パスキー管理', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '自分のすべての端末からログアウト' })).toBeVisible()
})
test('停止後もGoogleで既存データ・空月・追加編集削除・CSV出力を利用できる', async ({ page }) => {
  await prepareGoogleMock(page, 'legacy-disabled')
  await googleLogin(page)
  await expect(page).toHaveURL(/\/\d{4}\/\d{2}/)
  await page.goto('/2026/02')
  await expect(page.getByText('副業', { exact: true })).toBeVisible()
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name: 'CSV出力' }).click()
  expect((await downloaded).suggestedFilename()).toBe('家計データ_2026年2月.csv')
  await page.goto('/2027/01')
  const section = page.locator('[data-section="income"]')
  await section.getByRole('button', { name: '項目を追加' }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByPlaceholder('例：食費、家賃、給与').fill('Google移行後収入')
  await dialog.getByPlaceholder('¥ 0').fill('12345')
  await dialog.getByRole('button', { name: /収入.*追加/ }).click()
  await expect(page.getByText('Google移行後収入', { exact: true })).toBeVisible()
  let row = page.getByTestId('item-row').filter({ hasText: 'Google移行後収入' })
  await row.hover()
  await row.getByRole('button', { name: /を編集/ }).click()
  dialog = page.getByRole('dialog')
  await dialog.locator('input[name="label"]').fill('Google更新後収入')
  await dialog.getByRole('button', { name: '更新', exact: true }).click()
  row = page.getByTestId('item-row').filter({ hasText: 'Google更新後収入' })
  await expect(row).toBeVisible()
  await row.hover()
  await row.getByRole('button', { name: /を削除/ }).click()
  await page.getByRole('button', { name: '削除する', exact: true }).click()
  await expect(row).toHaveCount(0)
})
