export const AI_DIAGNOSIS_LEASE_DURATION_MS = 2 * 60 * 1000
export const AI_DIAGNOSIS_GLOBAL_COOLDOWN_MS = 5 * 1000
export const AI_DIAGNOSIS_DAILY_LIMIT = 20
export const AI_DIAGNOSIS_MAX_CLASSIFICATION_LABELS = 100
export const AI_DIAGNOSIS_MAX_CATEGORY_EXPENSES = 100
